---
- name: Configure Raspberry Pi
  hosts: godspeed
  tasks:

    # Update and Upgrade
    - name: Run apt update and dist-upgrade
      ansible.builtin.apt:
        update_cache: yes
        upgrade: dist

    - name: Run apt full-upgrade
      ansible.builtin.apt:
        name: "*"
        state: latest
        force_apt_get: yes
        dpkg_options: force-confold,force-confdef

    # Edit config.txt
    - name: Add line to the top of /boot/config.txt
      ansible.builtin.lineinfile:
        path: /boot/config.txt
        line: 'dtparam=i2c_arm=on'
        insertbefore: BOF  # BOF means beginning of file

    - name: Add lines to the bottom of /boot/config.txt
      ansible.builtin.blockinfile:
        path: /boot/config.txt
        block: |
          [pi02]
          arm_freq=1200

    # Ensure pip3 is installed
    - name: Ensure pip3 is installed
      ansible.builtin.apt:
        name: python3-pip
        state: present

    # Upgrade pip
    - name: Upgrade pip
      ansible.builtin.command:
        cmd: python3 -m pip install --upgrade pip

    # Install additional packages
    - name: Install additional packages
      ansible.builtin.apt:
        name:
          - python3-smbus
          - i2c-tools
        state: present

    # Install python packages using pip3
    - name: Install smbus2 using pip3
      ansible.builtin.pip:
        name: smbus2
        executable: pip3

    - name: Install Flask using pip3
      ansible.builtin.pip:
        name: Flask
        executable: pip3

    - name: Install RPi.GPIO using pip3
      ansible.builtin.pip:
        name: RPi.GPIO
        executable: pip3

    # Perform git pull on localhost for X1C-Actively-Heated-Chamber
    - name: Update X1C-Actively-Heated-Chamber repo on localhost
      ansible.builtin.git:
        repo: 'https://github.com/travisws/X1C-Actively-Heated-Chamber.git'
        dest: '/root/X1C-Actively-Heated-Chamber/'
        force: yes
        update: yes
      delegate_to: localhost

    # Copy X1C-Actively-Heated-Chamber folder to Raspberry Pi
    - name: Copy X1C-Actively-Heated-Chamber folder to Raspberry Pi
      ansible.builtin.copy:
        src: /root/X1C-Actively-Heated-Chamber/X1C-Actively-Heated-Chamber
        dest: /root/X1C-Actively-Heated-Chamber
        owner: root
        group: root
        mode: '0755'
        recursive: yes

    # Copy service file
    - name: Copy printer.service to Raspberry Pi
      ansible.builtin.copy:
        src: printer.service
        dest: /lib/systemd/system/
        owner: root
        group: root
        mode: '0644'

    # Enable and start godspeed-startup service
    - name: Enable and start service on the Raspberry Pi
      ansible.builtin.systemd:
        name: printer.service
        enabled: yes
        state: started

    # Reboot the system
    - name: Reboot Raspberry Pi
      ansible.builtin.reboot: